### ISSUE TITLE
可以Post-training quantization 训练后量化压缩吗？

### ISSUE THREAD

**Issue by tianhaoyue** [666DZY666/micronet#29]
您好，我目前所做的项目训练好的.pth格式的目标检测模型有460兆左右，希望对其进行压缩处理。请问对于训练后的模型，如.pth模型文件，可以应用您的方法对其进行压缩吗？
如果是边训练边量化，我能否在一个基于MaskRcnn的而且是斜框检测的目标检测网络中应用您的方法去实现模型的压缩呢?非常希望您能回复我的问题，万分感谢！

**Comment by 666DZY666** [comment]
1、ptq可参考deploy-tensorrt部分;
2、可以试试先把backbone量化看看效果。(使用方法参考，使用_迁移)

**Comment by JSnobody** [comment]
@tianhaoyue PQT目前适合做8-bit量化，4-bit量化效果不太好。
