### ISSUE TITLE
请问其中QAT和QAFT的区别是什么呢

### ISSUE THREAD

**Issue by wmkai** [666DZY666/micronet#84]
在我理解中，QAT应该是包含QAFT的？求解答

**Comment by wmkai** [comment]
还有一个问题就是bn_fuse_calib有什么好处吗，我理解这个设置就是使用batch的统计量，如果直接设置为false，直接使用running的统计量是不是会更好点呢。

**Comment by 666DZY666** [comment]
1、QAT或PTQ后的QAFT阶段会冻结BN的统计参数和模型的量化参数，可以提升量化训练最终效果；
2、bn_fuse_calib是为了解决量化训练中的抖动，具体可参考Quantizing deep convolutional networks for efficient inference: A whitepaper中的BN融合部分。
